### ISSUE TITLE
部分结果不正确

### ISSUE THREAD

**Issue by tongyifan** [Rhilip/ipv6wry-php#2]
举例：240e:321:c82:a300:c0f8:710f:63d0:8abf
代码如下：
```php
<?php
require "vendor/autoload.php";

use Rhilip\Ipv6Wry\IpLocation;

$ip = "240e:321:c82:a300:c0f8:710f:63d0:8abf";
print_r(IpLocation::searchIp($ip));
```
```
Array ( [ip] => 240e:321:c82:a300:c0f8:710f:63d0:8abf [area] => � 中国台湾省台北市 )
```

但是在ZX网站上查询结果为「中国青海省 中国电信公众宽带」

**Comment by Rhilip** [comment]
问题出在 https://github.com/Rhilip/ipv6wry-php/blob/4e10d465a3356ef52f332e1a35d19a59c9d7cf49/src/IpLocation.php#L285
此处传入 readInt()的$size值是 3 (`$this->osLen`)， 而 v0.1.1 对 3 bytes 时使用的unpack format 是 `v` 是错误的。（`v` 只处理 16 bit，导致存在1 bytes并没有被unpack出来）

`v0.1.2` 对其的处理是当`$size = 3` 时，额外补一位当成 4 bytes来处理

https://github.com/Rhilip/ipv6wry-php/blob/5bed54a8d7f6daf15784edf7727ec69c07ad51dc/src/IpLocation.php#L152-L162

其实也可以考虑将所有的均补齐到 8 bytes ，对应方法如下

```php
private function readInt(int $offset = 0, int $size = 8): int
    {
        $s = $this->read($offset, $size);

        while (strlen($s) < 8) {
            $s .= "\x00";
        }

        return unpack('P', $s)[1];
    }
```
